version: '2'
services:

  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    ports:
      - "80:80"
    volumes:
      - ./src/:/code
      - ./services/web/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build:
      context: ./services/php-fpm
    container_name: lemp_php
    volumes:
      - ./src/:/code
    networks:
      - code-network

  mariadb:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./services/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: bd_mariadb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    networks:
      - code-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha

      PMA_HOST: mariadb
      PMA_USER: usuario
      PMA_PASSWORD: senha
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
